### ISSUE TITLE
Not possible to use "awsvpc" network mode

### ISSUE THREAD

**Issue by n473-** [infrablocks/terraform-aws-ecs-service#7]
In order to make use of "awsvpc", one needs to specify a network configuration. This cannot be done through the task definition template itself; as far as I understand it must be set at the task definition level. 

This should be a relatively simple fix (he said, naively). Provide an input variable for `network_configuration` that accepts the [relevant Terraform block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#network_configuration), and modify `task_definition.tf` to include `network_configuration = var.network_configuration`.

If I have time I'll try to submit a pull request with the relevant change.

**Comment by tobyclemson** [comment]
Hi @n473- 

This module supports network mode "awsvpc" already. In order to use it, you need to provide the `subnet_ids` var as the IDs of the subnets you want the tasks to be deployed into. The corresponding security group is created and attached for you automatically, optionally with some default rules. The ID of that security group is output so you can attach further rules.

Hope this helps,
Thanks,
Toby

**Comment by n473-** [comment]
Thanks @tobyclemson for the quick and helpful response! `subnet_ids` wasn't listed as an input in the README; I should've checked the actual variables.tf file much earlier.

Thanks again!

**Comment by tobyclemson** [comment]
Ah! Sorry about that, I’ll get it updated. The listing on the Terraform registry is more reliable: https://registry.terraform.io/modules/infrablocks/ecs-service/aws/latest
